on: push

permissions:
  contents: write
  actions: write

jobs:
  update-files:
    name: "Generate new files"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: "Create Index.json"
        run: |
          cd .generator
          bun run convert.ts

      - name: "Create README.md"
        run: |
          bash .github/create_readme.sh

      - name: "Push changes"
        run: |
          git add .
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "CI/CD: Apply changes [skip ci]"
          git push
