on: push

jobs:
  update-files:
    name: "Generate new files"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Create Index.json"
        run: |
          bash .github/create_index_json.sh

      - name: "Create README.md"
        run: |
          bash .github/create_readme.md

      - name: "Push changes"
        run: |
          git add .
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "CI/CD: Apply changes [skip ci]"
          git push
